### ISSUE TITLE
Release for Magento 2.2

### ISSUE THREAD

**Issue by MarcusWolschon** [degdigital/magento2-customreports#17]
The latest release required:
"magento/framework": "~100.1.1"

However Magent0 2.2 has a framework 101.x.x
So to upgrade to Magento 2.2 a new version of this module is needed, so composer lets us do the upgrade.

**Comment by sw-tt-rohanprajapati** [comment]
Hello,

How to add or apply custom filter or from/to date filter in this?

Thanks,
Rohan.

**Comment by MarcusWolschon** [comment]
Here are the things that need to be checked to allow PHP 7.2 in composer.json
http://php.net/manual/de/migration72.incompatible.php

Since PHP 7.2 and 7.1 can't be used with Magento on the same server due to
libcurl3 and libcurl4 conflicting, it's nothing I can do on my server and create a pull request for. :(

**Comment by MarcusWolschon** [comment]
Looks like we have to switch to one of the forks

https://github.com/degdigital/magento2-customreports/network

But none  of the forks seem to have anything bug PHP 7.1 in their composer.json 
and with the libcurl -limitation testing it on PHP7.2 requires setting up a new webserver with magento and actual data to run reports on a separate machine.

**Comment by jantzenw** [comment]
Sorry for the delay. This issue was resolved a while back but this issue was not updated. Use version 1.2 or the master branch for Magento 2.2 compatibility.
