### ISSUE TITLE
Comptability with Magento 2.3 ?

### ISSUE THREAD

**Issue by angelflo** [degdigital/magento2-customreports#18]
Hi,
Please can you tell me if your extension has been tested and work with last release of Magento 2.3 (who need php 7.2) ?
thx a lot for your job and to share it !

**Comment by MarcusWolschon** [comment]
The current release and the HEAD 
https://github.com/degdigital/magento2-customreports/blob/master/composer.json
still require PHP 7.1 
so changes need to be made to make it compatibel with 7.2 even if it's just a test-run and changing the composer.json.

**Comment by MarcusWolschon** [comment]
Duplicate of #19

**Comment by jantzenw** [comment]
Sorry for the delay. This issue was resolved a while back but this issue was not updated. Use version 1.2 or the master branch for Magento 2.3 compatibility.
