### ISSUE TITLE
 Is it compatible with Magento 2.4?

### ISSUE THREAD

**Issue by dlauria11** [degdigital/magento2-customreports#25]
Is it compatible with Magento 2.4?

**Comment by jantzenw** [comment]
Hi @dlauria11,

Sorry for the delay. Yes the module is compatible with Magento 2.4. FYI there will be a new version of the extension coming soon that has been tested more extensively on 2.4 than the current version.

**Comment by YiffyToys** [comment]
@jantzenw what's the status of that new release? Your message is 11 month old.
Last release is still 1.1.5.1 on 26 Apr 2017 .

**Comment by jantzenw** [comment]
Sorry, the master branch was updated but a tag was not created. A tag has now been created, for version "1.2". Try that.

2.0 will be released soon: https://github.com/degdigital/magento2-customreports/pull/34. This introduces support for remote file drops.
