### ISSUE TITLE
unexpected 'AutomatedExportRepositoryInter' (T_STRING)

### ISSUE THREAD

**Issue by dtamajon** [degdigital/magento2-customreports#26]
Latest version has multiple errors regarding to Model/AutomatedExport/Cron.php:

1.- Uncaught Error: Class 'Xtento\OrderExport\Model\AbstractAutomaticExport' not found
Xtento is not a regular class found in Magento. I found it is related to a commercial module.

2.- unexpected 'AutomatedExportRepositoryInter' (T_STRING)
The syntax used is not compatible with PHP 7.3

Error regarding to Model/ResourceModel/AutomatedExport.php:
3.- unexpected 'AutomatedExportLinkFactory' (T_STRING)
The syntax used is not compatible with PHP 7.3

Error regarding to Model/Service/CreateDynamicCron.php:
4.- unexpected 'ValueFactory' (T_STRING)
The syntax used is not compatible with PHP 7.3

Error regarding to Model/Service/DeleteDynamicCron.php:
5.- unexpected 'ValueFactory' (T_STRING)
The syntax used is not compatible with PHP 7.3

**Comment by lucaspaiva1** [comment]
Same problem here.

**Comment by ggm-dev** [comment]
Same issue here - did anyone find a resolution?

**Comment by dtamajon** [comment]
We are working in a fork until the problem is solved in main project:
https://github.com/litesolutions/magento2-customreports

**Comment by jantzenw** [comment]
Hi,

Sorry for the delay. These issues should be fixed with the latest commits in the master branch. Please let me know if there's something I missed.

**Comment by jantzenw** [comment]
Per above, this issue should have been fixed in the latest master branch, or in version 1.2. 

However, version 2.0 (releasing soon) drops support for PHP 7.3 and reintroduces typed properties.
