### ISSUE TITLE
Please create a new release

### ISSUE THREAD

**Issue by peterjaap** [degdigital/magento2-customreports#32]
The latest tag is from April 2017 (https://github.com/degdigital/magento2-customreports/tags) but the latest commit is from July 13th.

**Comment by jantzenw** [comment]
Created tag 1.2 on a later commit in the master branch.

2.0 will be released soon: https://github.com/degdigital/magento2-customreports/pull/34. This will not be on the master branch to avoid breakages for users on PHP 7.3 depending on the master branch.
