### ISSUE TITLE
ACL doesn't fully work when assigned specific action to user role

### ISSUE THREAD

**Issue by mikelhsia** [degdigital/magento2-customreports#4]
![1](https://user-images.githubusercontent.com/8870278/27417533-b1389404-5747-11e7-9b28-16ee50c88cde.png)

This tool perfectly works on our project. However, while we tried to assign action to one single user role that doesn't have all privilege, the corresponding action shows nothing in the custom report list.

**Comment by akosglue** [comment]
is this solved? why is it closed?
